Add fly mode to debug
tsoding/something pull request #263
Opened 2020-11-06 10:30 UTC by kolumb

~Press F to pay respects to gravity.~
To enable fly mode, press `F` in debug mode.
Press `W` and `S` to accelerate in vertical direction.

2020-11-08 10:58 UTC, rexim requested changes
I don't really like the feeling of the controls. They are very non-intuitive. I think it would be better to implement it like so: you hold the key -> you are moving, you don't hold the key -> you are not moving.

Plus the trailing camera makes it inconvenient to move around. Can we disable it in the fly mode?

2020-11-08 19:31 UTC, kolumb commented
I also disabled collision detection for player in fly mode.

2020-11-16 11:42 UTC, rexim approved these changes

2020-11-16 11:44 UTC, rexim commented
@kolumb looks good to me :+1: Thank you for your contribution!

2020-11-16 11:45 UTC, merged